version: "3.8"
services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./backend:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs  
    depends_on:
      - backend

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./mongo.env
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    container_name: backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./backend:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email enginkaan6@gmail.com --agree-tos --no-eff-email --force-renewal -d workflowapp.store -d www.workflowapp.store   
volumes:
  data: 
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/apps/workflow-app/dhparam/
      o: bind
