version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./mongo.env
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    container_name: backend
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/app/src # bind mount
      - ./frontend/index.html:/app/index.html # bind mount
      - ./frontend/tailwind.config.js:/app/tailwind.config.js # bind mount
    stdin_open: true # -it => input part
    tty: true # -it => terminal part
    depends_on:
      - backend
volumes: 
  data: 
