version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./mongo.env
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    container_name: backend
volumes: 
  data: 
