name: Deploy
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          script_stop: true
          command_timeout: 200m
          script: 
            - cd /home/apps/workflow-app
            - git pull
            - docker-compose -f docker-compose-prod.yaml up -d --build